version: '3.8'

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aitabbble
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aitabbble-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/aitabbble
    depends_on:
      - postgres
    networks:
      - aitabbble-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend
    networks:
      - aitabbble-network
    restart: unless-stopped

networks:
  aitabbble-network:
    driver: bridge

volumes:
  postgres_data: 